[package]
name = "socketioxide"
version = "0.6.0"
edition = "2021"
rust-version = "1.63.0"


authors = ["Théodore Prévot <"]
description = "Socket IO server implementation in rust as a Tower Service."
repository = "https://github.com/totodore/socketioxide"
homepage = "https://github.com/totodore/socketioxide"
keywords = ["socketio", "tower", "axum", "hyper", "websocket"]
categories = [
    "asynchronous",
    "network-programming",
    "web-programming::websocket",
]
license = "MIT"
readme = "../README.md"


[dependencies]
engineioxide = { path = "../engineioxide", version = "0.6.0", default-features = false }
futures = "0.3.27"
tokio = "1.26.0"
serde = { version = "1.0.155", features = ["derive"] }
serde_json = "1.0.94"
tower = { version = "0.4.13", default-features = false }
http = "0.2.9"
http-body = "0.4.5"
thiserror = "1.0.40"

# Extensions
dashmap = { version = "5.4.0", optional = true }

# Tracing
tracing = { version = "0.1.37", optional = true }

# Hyper v0.1
http-body-v1 = { package = "http-body", version = "1.0.0-rc.2", optional = true }
hyper-v1 = { package = "hyper", version = "1.0.0-rc.4", optional = true, features = [
    "server",
    "http1",
    "http2",
] }

[features]
default = ["v5"]
v5 = ["engineioxide/v4"]
v4 = ["engineioxide/v3"]
test-utils = []
tracing = ["dep:tracing", "engineioxide/tracing"]
extensions = ["dep:dashmap"]
hyper-v1 = ["engineioxide/hyper-v1", "dep:http-body-v1", "dep:hyper-v1"]

[dev-dependencies]
engineioxide = { path = "../engineioxide", version = "0.6.0", features = [
    "v3",
    "v4",
    "test-utils",
] }
axum = "0.6.18"
tokio = { version = "1.26.0", features = [
    "macros",
    "parking_lot",
    "rt-multi-thread",
] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tokio-tungstenite = "0.20.0"
hyper = { version = "0.14.25", features = [
    "http1",
    "http2",
    "server",
    "stream",
    "runtime",
    "client",
] }
criterion = { version = "0.5.1", features = ["html_reports"] }

[[bench]]
name = "packet_encode"
path = "benches/packet_encode.rs"
harness = false
[[bench]]
name = "packet_decode"
path = "benches/packet_decode.rs"
harness = false
