[package]
name = "engineioxide"
description = "Engine IO server implementation in rust as a Tower Service."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
license.workspace = true

[dependencies]
futures.workspace = true
http.workspace = true
http-body.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tower.workspace = true

async-trait = "0.1.66"
base64 = "0.21.0"
bytes = "1.4.0"
hyper = "0.14.25"
pin-project = "1.0.12"
tokio-tungstenite = "0.20.1"
rand = "0.8.5"

# Tracing
tracing = { workspace = true, optional = true }

# Engine.io V3 payload
memchr = { version = "2.5.0", optional = true }
unicode-segmentation = { version = "1.10.1", optional = true }

# Hyper v1.0
hyper-v1 = { package = "hyper", version = "1.0.0-rc.4", optional = true }
http-body-v1 = { package = "http-body", version = "1.0.0-rc.2", optional = true }
hyper-util = { git = "https://github.com/hyperium/hyper-util.git", optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "parking_lot"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
hyper = { version = "0.14.25", features = [
    "http1",
    "http2",
    "server",
    "stream",
    "runtime",
    "client",
] }

[features]
default = ["v4"]
v4 = []
v3 = ["memchr", "unicode-segmentation"]
test-utils = []
tracing = ["dep:tracing"]
hyper-v1 = ["dep:hyper-v1", "dep:http-body-v1", "dep:hyper-util"]
