[package]
name = "socket-io-server-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
engineio-server = { path = "../engineio-server" }
axum = { version = "0.6.10" }
tokio = { version = "1.13.0", features = ["full"] }
tower = { version = "0.4.13" }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing = "0.1.37"

[[example]]
name = "axum-echo"
path = "src/axum_echo.rs"
