[workspace]
members = ["*"]
resolver = "2"


[workspace.package]
version = "0.6.0"
edition = "2021"
rust-version = "1.65.0"
authors = ["Théodore Prévot <"]
repository = "https://github.com/totodore/socketioxide"
homepage = "https://github.com/totodore/socketioxide"
keywords = ["socketio", "tower", "axum", "hyper", "websocket"]
categories = [
    "asynchronous",
    "network-programming",
    "web-programming::websocket",
]
license = "MIT"
