[package]
name = "engineioxide-e2e"
version = "0.6.0"
edition = "2021"

[dependencies]
engineioxide = { path = "../../engineioxide", default-features = false, features = [
    "tracing",
] }
hyper = { version = "0.14.26" }
tokio = { version = "1.13.0", features = ["full"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing = "0.1.37"
serde_json = "1.0.95"
futures = "0.3.27"

[[bin]]
name = "engineioxide-e2e"
path = "engineioxide.rs"
bench = false

[features]
v3 = ["engineioxide/v3"]
v4 = ["engineioxide/v4"]
