[package]
name = "engineioxide-e2e"
version = "0.6.0"
edition = "2021"

[dependencies]
engineioxide = { path = "../../engineioxide", default-features = false, features = [
    "tracing",
    "hyper-v1",
] }
hyper-v1 = { package = "hyper", version = "1.0.0-rc.4", features = [
    "server",
    "http1",
    "http2",
] }
hyper-util = { git = "https://github.com/hyperium/hyper-util.git" }
hyper = { version = "0.14.26" }
tokio = { version = "1.13.0", features = ["full"] }
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
tracing = "0.1.37"
serde_json = "1.0.95"
futures = "0.3.27"

[[bin]]
name = "engineioxide-hyper-v1-e2e"
path = "engineioxide-hyper-v1.rs"

[[bin]]
name = "engineioxide-hyper-v04-e2e"
path = "engineioxide-hyper-v04.rs"

[features]
v3 = ["engineioxide/v3"]
v4 = ["engineioxide/v4"]
