[package]
name = "hyper-v1-echo"
version = "0.6.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
engineioxide = { path = "../../engineioxide", features = [
    "hyper-v1",
    "tracing",
] }
hyper-v1 = { package = "hyper", version = "1.0.0-rc.4", optional = true, features = [
    "server",
    "http1",
    "http2",
] }
hyper-util = { git = "https://github.com/hyperium/hyper-util.git" }
tokio = { version = "1.33.0", features = ["full"] }
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tracing = "0.1.37"
serde = "1.0.188"
serde_json = "1.0.107"
futures = "0.3.28"

[[bin]]
name = "hyper-v1-echo"
path = "hyper_v1_echo.rs"
